# Generated by Django 2.2 on 2020-03-13 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property_Name', models.CharField(default=' ', max_length=50)),
                ('Property_Description', models.CharField(default=' ', max_length=50)),
                ('Property_Guest_Capacity', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Property_Street', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Property_City', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Property_State', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Price', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('No_of_Rooms', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('No_of_Bathrooms', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Total_Area', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Garage_Size', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('No_of_Floors', models.CharField(blank=True, default=' ', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Report_TimeDate', models.DateTimeField(blank=True, null=True)),
                ('Property_Status_Description', models.CharField(blank=True, max_length=50, null=True)),
                ('Expenses', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Comments', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Maintenance_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Property_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airbnbapp.Properties')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trans_Time_Date', models.DateTimeField(blank=True, null=True)),
                ('Trans_Type', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Transaction_Token', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Notes', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Customer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Property_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airbnbapp.Properties')),
                ('Trans_Amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airbnbapp.Property_Status')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_From', models.DateTimeField(blank=True, null=True)),
                ('Date_To', models.DateTimeField(blank=True, null=True)),
                ('No_Of_Guest', models.IntegerField(blank=True, null=True)),
                ('Customer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Property_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airbnbapp.Properties')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Available', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Availability_StartTime', models.DateTimeField(blank=True, null=True)),
                ('Availability_EndTime', models.DateTimeField(blank=True, null=True)),
                ('Property_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airbnbapp.Properties')),
            ],
        ),
    ]
